### PR TITLE
[WIP] Clean status of closed file descriptors

### PR DESCRIPTION
**Pull request by sghctoma**
Calling `close()` on a file descriptor will remove any kevents that reference the descriptor, but the saved state of that file descriptor remains. This causes trouble, because fd numbers are reused, and later you are not able to add an event that references a file descriptor with the same numerical value as a closed one.

This commit aims to solve this by deleting the status of fds that return `ENOENT` to an `EV_RECEIPT` at the start of `epoll_ctl`. This might not be the ideal solution, but every angle I could think of is covered, and I've been using this patch with sway for three days now.

It's important, that this behaviour is not exactly the same as `epoll`'s on Linux, because the original removes an fd from an `epoll` set only if there are no other file descriptors open for the underlying file description (see Q6 in `epoll`'s man, and also this link: https://idea.popcount.org/2017-03-20-epoll-is-fundamentally-broken-22/). I don't know how to mimic that behaviour, nor if it is even possible.

---

BTW, if you are interested, this was the cause of the issue I mentioned in #4 about loosing input when switching VTs from, and back to sway. I have narrowed it down to a libinput_resume() failure after a successful libinput_suspend(). Roughly this is what was happening:

 1. `libinput_suspend()` calls `udev_input_disable()`
 2. `udev_input_disable()` calls `udev_monitor_unref()`, which closes the fds that were at some point created by `udev_monitor_new_from_netlink()`
 3. `udev_input_disable()` calls `libinput_remove_source()`
 4. `libinput_remove_source()` calls `epoll_ctl()` to remove the already closed fd
 5. `epoll_ctl()` fails to remove the already closed fd

 6. `libinput_resume()` calls `udev_input_enable()`
 7. `udev_input_enable()` calls `udev_monitor_new_from_netlink()`, which creates the fds, which get the same numerical values as the previous ones (no other fds were created between)
 8. `udev_input_enable()` calls `libinput_add_fd()`
 9. `libinput_add_fd()` calls `epoll_ctl()` to add the fd to the epoll set
 10. `epoll_ctl` fails, because the fd is already in the set, because removing it in step 5 failed

With this patch, step 5. still fails (as it does on Linux), but it does not matter, because that event is already removed from the `kqueue`, and we are cleaning up it's state.

### CODE REVIEW

**Comment by jiixyj** [comment]
Thanks for the patch and the detailed description of the bug! Can you add a small test to `epoll-test.c`?

I fear that the EVFILT_READ/EV_RECEIPT call will set the `udata` to `0`, though, losing the originally set `udata`. There seems to be no clean way to ask the kqueue API to not touch the `udata`, sadly. I'll have another look later.

There might be another way to fix this particular bug. Can you try something like this? This won't automatically detect if a fd was closed, but at least it should reset the flags to `0` if `epoll_ctl` tries to remove an already closed fd.
```
diff --git a/src/epoll.c b/src/epoll.c
index 771a7f8..70256a1 100644
--- a/src/epoll.c
+++ b/src/epoll.c
@@ -301,6 +301,9 @@ epoll_ctl(int fd, int op, int fd2, struct epoll_event *ev)
 		}
 
 		if (kev[i].data != 0) {
+			if (i == 0 && kev[i].data == ENOENT) {
+				kqueue_save_state(fd, fd2, 0);
+			}
 			errno = kev[i].data;
 			return -1;
 		}
```

**Comment by sghctoma** [comment]
Ah, yes, I think you are right about `udata` being cleared. Maybe an `EVFILT_USER` could be added/deleted whenever an `EVFILT_READ`/`EVFILT_WRITE` pair is added/deleted, and we can check the existence of that? It's just a vague idea, I will need to think this through (sometimes `kqueue` still confuses me, despite reading through the man many times).
I will also add some tests.

I didn't try your patch yet, but I think it won't work, because `kqueue_save_state` will never be executed: if the fd was closed, the write filter was also deleted, so the `continue` at line 300 is executed. This wouldn't be a good general solution anyways, because e.g. an `EPOLL_CTL_ADD` -> close fd -> open fd -> `EPOLL_CTL_ADD` sequence would still fail.

**Comment by jiixyj** [comment]
I've merged your tests and added that line that clears the internal state when trying to remove an already closed fd. But calling `EPOLL_CTL_DEL` is still needed to make the test pass, though. The `EPOLL_CTL_ADD -> close fd -> open fd -> EPOLL_CTL_ADD` sequence still won't work...

At least the libinput use case with the VT switching should work now (although I haven't tested it).

Thanks again!

**Comment by jiixyj** [comment]
Please reopen or create a new PR if you have any other ideas!

**Comment by jiixyj** [comment]
FYI: I've just fixed an issue that could be related in https://github.com/jiixyj/epoll-shim/commit/1605b570d28d9ce96b878e0aeab9f1a2edf3eb92. I hit this while creating/destroying evdev devices in `/dev/input/`. At some point libinput tried to EPOLL_CTL_DEL an already closed fd. The fstat call would complain and the fd would not be removed properly from the epoll instance. For some reason the old fix didn't catch this. Probably some race related to threading...

**Pull request closed without merging**
